#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
# Build as
# TODO(damondouglas): consider different directory with single Dockerfile or cloudbuild.yaml so that the command below uses gcloud builds.
# docker buildx build -t <image URL> -f Dockerfile-distroless --build_arg=BASE=<template launcher image URL> .
ARG BASE
FROM ${BASE} AS base
ENV LANG=C.UTF8

FROM gcr.io/distroless/python3-debian12 AS final

# Contains template code such as main.py.
COPY --from=base /template /template

# Prevents internal errors found with distroless container images and Flex templates.
COPY --from=base /usr/lib/locale /usr/lib/locale

# Contains header files needed by the Python interpreter.
COPY --from=base /usr/local/include /usr/local/include

# Contains the Python interpreter executables.
COPY --from=base /usr/local/bin /usr/local/bin

# Contains the Python library dependencies.
COPY --from=base /usr/local/lib /usr/local/lib

# Python standard library modules.
COPY --from=base /usr/lib/python* /usr/lib/.

# Contains additionally required files.
COPY --from=base /opt /opt

ENV PATH "$PATH:/usr/local/bin"

ENTRYPOINT ["/opt/google/dataflow/python_template_launcher"]